FROM python:3.7.2-slim

# instalando dependencias
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean



# estableciendo directorio de trabajo
WORKDIR /usr/src/app

# agregando e instalando requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# agregando entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh

# agregando app
COPY . /usr/src/app

# ejecutar server
CMD ["/usr/src/app/entrypoint-prod.sh"]